sudo: false
osx_image: xcode11
xcode_sdk: iphonesimulator13.0
language: objective-c
xcode_project: Pins.xcodeproj

script:
  - xcodebuild test -project Pins.xcodeproj -scheme Pins_iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.0'
  - xcodebuild test -project Pins.xcodeproj -scheme Pins_macOS -destination 'platform=OS X,arch=x86_64'
